### PR TITLE
Moved variable defs to external file to share between setup and cleanup ...

### PR DESCRIPTION
**Pull request by tljohnsn**
...scripts.

Added support for NATNET parameter in case of conflicts with 10.0.2 network

Added failover clocksource to grub to prevent problems with virtualbox

### CODE REVIEW

**Comment by casr** [comment]
Doh! I think some files didn't make it through on the commit :)

**Comment by casr** [comment]
These also seem like they will be unrelated commits. Would you mind splitting them up in some logical way as separate pull requests if more discussion needs to be done on each one? Thanks!

**Comment by casr** [comment]
ea098c4416fc8d827a98997c6588f63e23fe890f

**Comment by tljohnsn** [comment]
Sorry - I should have split them up better.  Thanks for cleaning them up.

Trent

**Comment by casr** [comment]
Hey Trent,

What did you mean by "Added support for NATNET parameter in case of conflicts with 10.0.2 network"?

**Comment by tljohnsn** [comment]
My home network is in 10.0.2 so the kickstart will not work unless I use an alternate network.

**Comment by casr** [comment]
All work here seems to be integrated now so I'm closing this.

**Pull request closed without merging**
